### ISSUE TITLE
different variants

### ISSUE THREAD

**Issue by e3rd** [e3rd/fb-getridad#2]
Máme různé varianty, jak mohou data-pagelet vypadat

**Comment by kaha0** [comment]
Nezachycený post: 
[html1.txt](https://github.com/e3rd/fb-getridad/files/7085420/html1.txt)

**Comment by e3rd** [comment]
Zkus aktuálního mastera – funguje ti to? :)

**Comment by kaha0** [comment]
Jo, teď už je skrytý všechno.

**Comment by kaha0** [comment]
Zkusil jsem manuálně změnit launcher.js na předchozí verzi a to opět funguje správně. Takže někde v tomhle je chyba:
`if (n.tagName === "SPAN" && n.style.top === '3em' &&
        (Array.from(n.parentElement.querySelectorAll('span')).filter(s => s.style.top !== '3em').map(s => s.textContent).join("").includes(lang["Sponsored"].slice(1))
            || n.textContent.length === 1 && n.nextElementSibling.textContent.length === 1)) {`

**Comment by e3rd** [comment]
jakože předposlední verze ti jela dobře, poslední špatně, současná nejhůř, takže ses vrátil na předposlední? Mně se teď reklamy dva dny nezobrazují vůbec – ani jedna (!) – tak to nemám zatím jak ozkoušet.

**Comment by kaha0** [comment]
Když je první řádek funkce is_garbage tohle:
`if ([lang["Sponsored"].slice(1), lang["Sponsored"]].includes(n.tagName === "SPAN" && n.style.top === '3em' && Array.from(n.parentElement.querySelectorAll('span')).filter(s => s.style.top !== '3em').map(s => s.textContent).join(""))) {`
tak funguje perfektně, když je tam to v komentu nahoře tak funguje špatně (jako ve screenshotu).

**Comment by e3rd** [comment]
Fakt jo, a nevynechává ti některé posty? Já myslel, že právě tenhle řádek ti některý post propustil.

**Comment by kaha0** [comment]
Ne, timhle řádkem to nebylo. Mám za to že jsi v lang indexoval špatnym klíčem "Suggested for you"?
Niméně se objevila nová věc:
![data-visualcompletion](https://user-images.githubusercontent.com/89856263/132139537-c6feebd2-1dcf-45b5-9256-bc0570a27634.png)
[data-visualcompletion.html.txt](https://github.com/e3rd/fb-getridad/files/7112247/data-visualcompletion.html.txt)

**Comment by kaha0** [comment]
Před chvílí jsem se přihlásil do fb a opět byly vidět posty "sponzorováno" i "návrhy pro vás". Tak jsem se odhlásil, zavřel soukromé okno, otevřel soukromé okno, přihlásil se do fb a nevyžádané posty byly skryté. Tady je html jednoho postu který předtím pronikl:
[html1.txt](https://github.com/e3rd/fb-getridad/files/7112382/html1.txt)

**Comment by e3rd** [comment]
* Zkus si dát aktuální verzi, co jsem nahrál. :) Přidal jsem tam to live gaming session.
* Kdykoli se stránka facebooku načte, do konzole se napíše: `[fb-getridad] Startup with lang: `. Pokud ti to někdy plugin nebude fungovat, čekni, zda je tam tenhle řádek – zjistíme tím, zda funguje špatně, nebo zda se z nějakého důvodu vůbec nespustil.
* inkriminovaný řádek jsem zkusil upravit na
```js
if (n.tagName === "SPAN" && n.style.top === '3em' &&
        (Array.from(n.parentElement.querySelectorAll('span')).filter(s => s.style.top !== '3em').map(s => s.textContent).join("").includes(lang["Sponsored"].slice(1))
        //    || n.textContent.length === 1 && n.nextElementSibling.textContent.length === 1
        )) {
        return true
    }
```

 s tím, že je zakomentovaná část, která ti mohla dělat problémy.

**Comment by kaha0** [comment]
Teď to vypadá, že vše funguje dobře. Díky

**Comment by e3rd** [comment]
Dej vědět, až zas nebude :D

**Comment by kaha0** [comment]
Opět skrz to pronikají nějaký posty. "[fb-getridad] Startup with lang:" se objevuje, i se správnym jazykem, viz screenshot. Přikládám html proniklých elementů.
![p](https://user-images.githubusercontent.com/89856263/133002981-0808b3e2-18dd-4d3b-8bb2-1021daf80cbd.png)
[html1.txt](https://github.com/e3rd/fb-getridad/files/7150295/html1.txt)
[html2.txt](https://github.com/e3rd/fb-getridad/files/7150296/html2.txt)

**Comment by e3rd** [comment]
ZKusíš aktuální master, jestli to funguje? Konečně jsem se k tomu dostal :)

**Comment by kaha0** [comment]
"Návrhy pro vás" jsou skrytý, ale všechny "Sponzorováno" (co jsem viděl) se zobrazují :( U tebe ve firefoxu je všechno skrytý?

Pár proniklých elementů:
[html1.txt](https://github.com/e3rd/fb-getridad/files/7216828/html1.txt)
[html2.txt](https://github.com/e3rd/fb-getridad/files/7216829/html2.txt)
[html3.txt](https://github.com/e3rd/fb-getridad/files/7216830/html3.txt)

**Comment by e3rd** [comment]
Jj, u mě jo, ale tyhle exempláře tam zas nemám. Zas ti vypadaj trošku jinak než minule :D Já nevim, jestli si na tobě FB pořád zkouší novej formát

**Comment by e3rd** [comment]
Zkusil jsem to vzít od podlahy, tak co teď? :D

**Comment by kaha0** [comment]
Teď to blokuje všechny nevyžádané, ale i některé žádoucí posty, například tenhle: 
[html.txt](https://github.com/e3rd/fb-getridad/files/7218076/html.txt)
Plus, od asi osmnáctého postu na zdi to blokuje úplně všechno.

**Comment by e3rd** [comment]
Neeeee :D Díky za post

**Comment by e3rd** [comment]
Von ti cpe slova "Sponzorováno" i do datumu! Tady v tom jsou znaky řetězce "20. září" i slova "Sponzorováno"!

![image](https://user-images.githubusercontent.com/6942231/134549735-345a357c-9bc0-4678-8485-24a947a45a52.png)

Vydal jsem teď další verzi, kdy navíc kontroluje, že jsou písmena slova Sponzorováno ve správném pořadí. Ale když to nepomůže, budu muset přijít na to, jak vyhodnotit styly (každý písmeno má jinej styl a některý styly je skrejvaj).

**Comment by kaha0** [comment]
Teď funguje perfektně! Snad to fb zase za pár dní nezmění :D

**Comment by e3rd** [comment]
Haha, to mám fakt radost! Tak se budu těšit, až to zas přestane :D

**Comment by kaha0** [comment]
Už to nastalo. Tenhle sponzorovaný post to neskrylo ( [ad.txt](https://github.com/e3rd/fb-getridad/files/7229494/ad.txt) ), a všechny následující posty zase skrylo, i ty žádoucí jako např. tenhle [notad.txt](https://github.com/e3rd/fb-getridad/files/7229500/notad.txt)

**Comment by e3rd** [comment]
Proč to ten jeden sponzorovaný neskrylo, netuším :o Ale zkusil jsem zase pořešit, aby to přestalo skrývat ty žádoucí. Zkusil bys aktuální master? A jestli se zase stane, že to bude zabíjet poctivé posty, tak si třeba zavideovoláme a já se podívám přímo do konzole, jak to u nich máš. (Nebo udělej screenshot, třeba písmena "p" ze "sponsored", jaké má computed styly – teď filtruju, že nesmí mít display: none a position-top 3em, ale možná fb skrývá ta písmena dalším stylováním. :) )

**Comment by kaha0** [comment]
Teď to háže tuhle chybovou hlášku: 
![err](https://user-images.githubusercontent.com/89856263/135331092-5ea3a60a-9515-4012-bafb-d2e534d7d736.png)
Jinak když dostanu příznivou mutaci fb (ve většině případů) tak funguje dobře, ale když dostanu nepříznivou tak jsou všechny posty "Sponzorováno" neskrytý, posty "Sponzorováno · platí za to" skrytý (co jsem zatim viděl), a "Návrhy" většinou skrytý ale minimálně jeden to taky neskrylo.

Zkusil jsem to ve firefoxu a tam mi to zatim fungovalo vždy. Tys to u sebe zkoušel v nějakym Chromiu? Určitě by se šiklo zjistit jestli původcem je chromium, nebo to že jsem zrovna já v množině lidí, který chce fb za každou cenu vnutit reklamy (nebo na nich testuje jak překonat adblock).

Při skrytých poctivých postech dám vědět.

**Comment by e3rd** [comment]
Chybová hláška by teď měla zmizet, zkus zkus

> příznivou mutaci fb (ve většině případů)

Počkej, ono vždycky nedostaneš správnou mutaci, správný jazyk? Na tom to stojí a padá. :o

> já to jedu v chromu a někdy zkouším ve firefoxu, ale DOM mi vypadá úplně totožně jako v chromu. Používám FB anglicky, napadlo mě, že odlišný DOM není ani tak prohlížečem, jako mutací.

**Comment by kaha0** [comment]
Haha, tohle je vtipný. Chtěl jsem napsat "Ne ne, jazyk je vždycky stejnej, myslel jsem variantu", ale...

Zalogoval jsem se do fb, vše funguje. Šel jsem do zpráv, šel jsem zpět na wall, všechny posty po prvním skrytý. Otevřu konzoli a:
![lang](https://user-images.githubusercontent.com/89856263/135344356-0971fdeb-bb53-4265-bbef-c529b7f34a82.png)

Z nějakýho důvodu se jazyk fb-getridad resetuje na angličtinu, a pak to z nějakýho důvodu skrývá všechny posty po prvním na zdi.

**Comment by kaha0** [comment]
Stává se to jen někdy, dost zřídka, nedokážu spolehlivě vyvolat znovu...

**Comment by e3rd** [comment]
Tak to je dost nadějné! V kódu jsem měl, že to čekalo půl vteřiny a když to nic nenašlo, dalo to angličtinu. Teď čeká až dvacet vteřin, dokud se neobjeví správný element a až pak to vyhodnotí jazyk. Zkus mastera teď :)

**Comment by kaha0** [comment]
Zatim vše vypadá ok. Dám vědět když se zase něco objeví (nebo neobjeví).

**Comment by e3rd** [comment]
Tak zatím vypadá dobře <3

**Comment by e3rd** [comment]
Já jsem to probral teď shora zdola a přišlo mi, že projít měl :D Tak jestli to jinak celkem funguje, tak to asi nebudu řešit. Když to bude moc často, budem muset vymyslet, jak to ladit na dálku

**Comment by kaha0** [comment]
Že projít měl nebo že ho to mělo zablokovat? Jo, je to jenom prkotina, stává se to jenom zřídkakdy a i tak je to jenom jeden post, tak to klidně nech. Od tý doby se to stalo ještě dvakrát, vždycky je to první post na zdi tak to zřejmě bude mít něco do činění s tim, ale nemá cenu se s tim moc babrat. Díky za add-on :)

**Comment by e3rd** [comment]
jj, zablokovat; jako že měl projít funkcí, která ho úspěšně zablokuje. Asi to bude teda prvním postem na zdi, budu o tom trochu vědět :)

**Comment by kaha0** [comment]
Ahoj, nová varianta :)
[fb.txt](https://github.com/e3rd/fb-getridad/files/8189069/fb.txt)

**Comment by e3rd** [comment]
šiit!

**Comment by kaha0** [comment]
Možná jsem měl zmínit, že se mi úplně změnil celej facebook. Teď vypadá takhle:
![fb](https://user-images.githubusercontent.com/89856263/158892983-a8d8952e-661e-48de-9772-4f8da51bd4d2.png)
Dal bych ruku do ohně za to, že když se změnil a současně přestal skývat sponzorovaný posty, zkontroloval jsem konzoli a `[fb-getridad] Startup with lang:` tam bylo. Ale teď už to tam neni, netušim proč. Zkusil jsem odinstalovat addon, restartovat prohlížeč, znova stáhnout a nainstalovat addon, pořád nic.

**Comment by kaha0** [comment]
Aha! Teď tam `[fb-getridad] Startup with lang:` je, ale se špatnym jazykem.
![fb](https://user-images.githubusercontent.com/89856263/158896004-80ee17b8-7f14-49b7-b740-f294d1c6300a.png)
Navíc mam 100% jistotu že v situaci v předchozím komentu to v konzoli nebylo.

**Comment by kaha0** [comment]
Zkusil jsem to znova a `[fb-getridad] Startup with lang:` opět v konzoli neni. Všimnul jsem si, že v konzoli je od samotnýho facebooku hromada chybovejch hlášek, jako ve screenshotu nahoře. Nemůže to mít vliv?

**Comment by kaha0** [comment]
Teď jsem nainstaloval firefox a dělá to přesně to samý. `[fb-getridad] Startup with lang:` se buď neobjeví vůbec, nebo `[fb-getridad] Lang is not sure.`. A taky 38 Uncaught Errors od facebooku samotnýho.

**Comment by kaha0** [comment]
`document.querySelector("input[type=search]")` vrátí null, proto se nenastaví jazyk a funkce `fetch_language` ani nic nezaloguje do konzole.

**Comment by kaha0** [comment]
Navíc jsem zjistil, že často se z nějakýho důvodu vůbec nenaloaduje launcher.js a nezačne se vykonávat, a neni to vinou facebooku. Zkusil jsem to v manifestu změnit na seznam.cz a upravit launcher.js aby něco zalogoval do konzole, a nic...

**Comment by kaha0** [comment]
Zkusil jsem to v čistý instalaci Ubuntu + Firefox, chová se naprosto stejně.

**Comment by kaha0** [comment]
Konečně dobrá zpráva! Když necham lang natvrdo nastavený na češtinu a odstranim funkci `fetch_language`, tak všechno funguje jak má. Takže zbývá jen vymyslet shibboleth tak, aby fungoval i v novym facebooku.

**Comment by e3rd** [comment]
Hej, tos to hrozně dobře vyzkoumal! Takže příspěvky zůstaly stejné, změnilo se ale políčko, z kterého dostáváme jazyk.

A když si tenhle kód

```
switch (shibboleth) {
        case "Hledejte na Facebooku":
            lang = LANG["cs"]
            break;
```

vyměníš za tenhle (o řádek víc)

```
switch (shibboleth) {
        case "Hledejte na Messengeru":
        case "Hledejte na Facebooku":
            lang = LANG["cs"]
            break;
```

tak se ten shibboleth chytne? Jo-li můžem vydat! :)

**Comment by kaha0** [comment]
Někdy jo, ale většinou ne, protože `document.querySelector("input[type=search]")` velmi často vrací null a pak funkce `fetch_language` úplně selže. Je zajímavý že v `lang` by v takovym případě měla zůstat defaultně nastavená čeština, ale jak vidno v [tomto komentáři](https://github.com/e3rd/fb-getridad/issues/2#issuecomment-1071505920) je tam kdovíproč angličtina a pak mi s českym facebookem nefunguje.

**Comment by e3rd** [comment]
Tyjo a doved bys přijít na nějaký volání, který jednoznačně určí jazyk, když ten `document.querySelector("input[type=search]")` ještě není ready? Jestli ne, tak můžeš zkusit zavolat `document.querySelector("input[type=search]")`, až když se stránka úplně načte, za chvíli? (Že bychom posunuli spuštění doplňku o pár vteřin ještě třeba...)

**Comment by kaha0** [comment]
Zavolat to později jsem zkoušel, mam pocit že když se zaloguju do facebooku a dostanu tu variantu která vrací null, tak vždycky vrací null. Napadlo mě jestli by to nešlo dělat bez šiboletu a kontrolovat každej element na přítomnost všech zakázaných stringů ("Sponsored", "Sponsorisé", "Sponzorováno", ...). To by bylo víc výpočetně náročný ale zase by se ušetřily všechny ty volání setTimeoutUntilTrue...

**Comment by kaha0** [comment]
Tak mě napadlo, nestačil by k určení jazyka třeba atribut lang elementu HTML?
![fblang](https://user-images.githubusercontent.com/89856263/159977164-934752d5-b7ec-4cab-9dd8-27918bc2a842.png)

**Comment by e3rd** [comment]
WOW, to je geniální, to bude VONO! Já tam mám lang="en" :)

**Comment by e3rd** [comment]
Předělal jsem to na ten tvůj html lang – zkusíš aktuální master? Já teď nemám žádný reklamy, abych to vyzkoušel... :D Jestli to pude, s dovolením zavřu tvůj #8 , protože celá část s shibolettem je fuč. @kaha0

**Comment by kaha0** [comment]
Jo, funguje perfektně, všechny sponzorovaný posty jsou skrytý :)

**Comment by e3rd** [comment]
Tak se uvidíme u další změny fb

**Comment by kaha0** [comment]
Zas prošel jeden post. Všechny ostatní sponzorovaný posty byly skrytý. Zajímavý je že jak mají většinou vedle slova "Sponzorováno" ikonku zeměkoule s popiskem "Veřejný", tak tenhle měl Ozubený kolečko a "Sdíleno s: Vlastní", tak mě napadlo jestli to nemůže mít vliv.
![p](https://user-images.githubusercontent.com/89856263/162642237-88b37b6c-9f59-45e3-a183-2006be48f1fc.png)

[html.txt](https://github.com/e3rd/fb-getridad/files/8460033/html.txt)

**Comment by kaha0** [comment]
Jéje, už posty pronikají hromadně. Zatim mam pocit že "Návrhy pro vás" zůstávají skrytý a ostatní pronikají všechny. Příklady proniklých postů:
[html1.txt](https://github.com/e3rd/fb-getridad/files/8487887/html1.txt)
[html2.txt](https://github.com/e3rd/fb-getridad/files/8487888/html2.txt)
[html3.txt](https://github.com/e3rd/fb-getridad/files/8487890/html3.txt)
[html4.txt](https://github.com/e3rd/fb-getridad/files/8487891/html4.txt)
[html5.txt](https://github.com/e3rd/fb-getridad/files/8487892/html5.txt)

**Comment by e3rd** [comment]
Darebáci! Musíš asi přežít aspoň do úterka, já to už nestihnu :(

**Comment by kaha0** [comment]
V pohodě, přežiju, stačí až budeš mít čas. Píšu to sem jenom abys moh vylepšovat tenhle projekt a udržovat ho up-to-date.

Jinak z toho co jsem vypozoroval to zatim vypadá, že všechny "Sponzorováno" nejsou skrytý, všechny "Sponzorováno, platí za to" i "Návrhy pro vás" jsou skrytý.

**Comment by kaha0** [comment]
Jop :) Teď mi skrývá všechny sponzorovaný, tak zase naviděnou příště.

**Comment by kaha0** [comment]
Tak už to facebook zase změnil. Podařilo se mi upravit kód tak aby blokoval i ty nový varianty, ale musel jsem k tomu použít element.computedStyleMap, což je něco co podporuje jenom Chromium :( Tak co teď?

**Comment by e3rd** [comment]
Hahá! Já to tu nezavřu! :D Tak sem postni zase ukázku tý varianty a třeba budu mít příští tejden taky čas se na tu vopičárnu podívat :D Vo element.computedStyleMap jsem teda jaktěživ neslyšel, teď to čtu a hustý.

**Comment by e3rd** [comment]
Hustý! Tak jsem si to prohlíd a pokorně nebudu dělat nic, než to začne vadit někomu dalšímu (jako třeba mně), protože to vypadá přesně na tu krásnou věc, s kterou můžu strávit celý vodpoledne :D . Třeba se mezitím API standardizuje a bude to fungovat i ve FF či tak.

**Comment by kaha0** [comment]
Plně s tebou souhlasím a podporuji tvojí pozici, computed styles klidně neřeš.

Nicméně dnes ráno vznikl novej problém: facebook se zase změnil. Zcela zmizelo "data-pagelet", takže neni na co zavolat check_garbage. Teď už lze posty na zdi identifikovat jen tím, že jejich rodič je element `<div role="feed">`, viz celej muj feed zde: [feed.txt](https://github.com/e3rd/fb-getridad/files/8728216/feed.txt)
Jinými slovy teď zas vidim všechny sponzorovaný posty, ale asi by to mělo jít snadno upravit, tak se na to zkusim podívat sám a když se mi to podaří vyřešit tak zase založim pull request.

**Comment by e3rd** [comment]
Co ty chudáku furt máš práce s tim! Seš jejich pokusnej králík! A vždycky když napíšu tady, tak ti to změněj tam! všim sis?

**Comment by kaha0** [comment]
Hotovo, ta verze v aktuálním pull requestu mi funguje. Zkus jestli ti taky funguje ve FF.

Jo, všim jsem si... taky mě napadlo jestli fb nesleduje projekty, který se snaží blokovat reklamy, a neadaptuje se jim...

**Comment by e3rd** [comment]
Asi by to mohl sledovat, věřím ale, že tenhle projekt nemá velkou publicitu (kromě spammerů, kteří našli mail na stránkách Add-onu Mozilly, ti mě zbožňujou). A mně se žádné psí kusy nedělají.

**Comment by kaha0** [comment]
Oni ani nemusí sledovat přímo tenhle tvuj konkrétní projekt, určitě jich existuje vícero a tipnul bych si že fungujou na stejnym principu, takže když fb obejde jeden "adblock" tak tim rozbije i velkou část jiných. A taky vždycky když fb něco změní tak dělají postupnej rollout, asi je pro ně těžký změnit něco všem uživatelům najednou, takže i to obcházení "adblocků" uživatelé dostávají ve vlnách... možná.

**Comment by e3rd** [comment]
Jenže ty seš pořád na mušce s těma divnejma zrůdnostma, kdežto já nepotřeboval změnu už celé měsíce – až teď jsem začal ten tvůj kód, co máš skoro měsíc. (Jako jo, třeba to tak nějak je, dávalo by to větší smysl, než že to dělají úplně náhodně.)

**Comment by kaha0** [comment]
Další změna: doteď jsem písmena stringu "Sponzorováno" detekoval tim, že měly style="order: x". Ale teď se začínají objevovat posty, který mají i to "order: x" schovaný tim že je to computed, stejně jako mají ty falešný, obfuskující písmena schovaný "top: 3em" a "display: none". V inkriminovaných postech mají písmena formu už jen `<div class="___">`. Takže by se to dalo vyřešit pomocí computedStyleMap, ale jen v chromiu, ve firefoxu by takový posty vždycky procházely. Co teď?

**Comment by kaha0** [comment]
>:)

**Comment by kaha0** [comment]
![fb](https://user-images.githubusercontent.com/89856263/180010687-28919eba-be5c-43c1-ac60-963b63d39f79.png)

letter.top == '0.013px' :D

**Comment by kaha0** [comment]
Tak už zase vidim úplně všechno :( Posty na zdi už nejsou přímými potomky elementu `&lt;div role="feed"&gt;`, tady v obrázku je označený sponzorovaný post:
![fb](https://user-images.githubusercontent.com/89856263/180979500-e8b7d839-db39-4c69-be36-248a27038085.png)

**Comment by kaha0** [comment]
Tak až do teď mi vše fungovalo úplně perfektně. Ale právě se objevila úplně nová věc:
![ad](https://user-images.githubusercontent.com/89856263/191618508-aec5ac5c-fc1d-41f5-91d0-d94746e3f0e4.png)
[ad.txt](https://github.com/e3rd/fb-getridad/files/9620708/ad.txt)

**Comment by e3rd** [comment]
:DD Co to furt zkoušej, darebáci! Kdyby místo toho radši zlepšovali UI, nebo dělali data uživatelů použitelnější!

**Comment by kaha0** [comment]
Mohl bys prosím updatenout ten addon na addons.mozilla.org? Současná verze mi neblokuje nic a firefox umožňuje to "Load unpacked addon" jenom dočasně, do příštího spuštění, takže bych musel při každym spuštění FF manuálě načítat addon z disku. Díky :)

**Comment by kaha0** [comment]
Tak jsem se na to ještě díval, a to co řeší muj pull request #20 hypoteticky podporuje i chromium... Firefox má `Element.openOrClosedShadowRoot` zatímco chromium má `chrome.dom.openOrClosedShadowRoot(element)`. Jenže když jsem zkusil to rozšíření upravit tak, aby pracovalo i v chromiu, browser vyhodil TypeError že funkce openOrClosedShadowRoot bere jen HTMLElement, a náš element &lt;use&gt; je SVGElement. Takže v chromiu to nebude fungovat, leda až to eventuálně nějak opraví. Píšu to sem jenom jako dokumentační komentář :)

**Comment by e3rd** [comment]
Na mě to v Chromu zatim nezkouší, tak netrpim :D

**Comment by kaha0** [comment]
Tak jsem tu zas. Facebook odteď arbitrárně zanořuje a seskupuje posty do divů, viz screenshot. Zkusim se na to sám podívat.
![fb](https://github.com/e3rd/fb-getridad/assets/89856263/9ac6883e-1df5-414d-939f-13a1d424be79)

**Comment by e3rd** [comment]
(Já jsem to možná vyřešil před pár týdny, ale testoval a nezveřejnil, zkusím dneska)

**Comment by e3rd** [comment]
Tenhle můj aktuální commit to náhodou řeší?

**Comment by kaha0** [comment]
Zatím nedokážu posoudit, facebook mi tu zanořovanou variantu dává jen zřídka. Jen chci poznamenat že český text pro FeedHeader je skutečně "Příspěvku v kanálu vybraných příspěvků" a ne "Příspěvky..." :)
![feedheader](https://github.com/e3rd/fb-getridad/assets/89856263/388104b8-fcb7-44f5-8483-8e7b380b0f21)

**Comment by e3rd** [comment]
Tak jsem se poprvé zasoustředil na ten tvůj post o zanořování; díky za barevné značení. To je teda děsivé, u mě je `<div class="x1lliihq">` prostě označení postu. Máme šanci, že ta aktuální verze bude fungovat i na zanořované, pokud se ze serveru divy načítají postupně.

**Comment by e3rd** [comment]
Kdyžtak zas otevři :) A přidal jsem debug mód, aby bylo zřejmé, co doplňkem prochází za HTML elementy.
