### ISSUE TITLE
Error: Cannot read properties of undefined

### ISSUE THREAD

**Issue by kaha0** [e3rd/fb-getridad#25]
fb-getridad allowed a sponsored post through. Upon closer inspection I found the cause is that `is_garbage` at some point gets called with `undefined` as parameter, tries to access its property `parents` and as a result exits with an error.

post: 
[html.txt](https://github.com/e3rd/fb-getridad/files/13853137/html.txt)

error location: 
![undefined](https://github.com/e3rd/fb-getridad/assets/89856263/45bd8c9d-0788-40de-b55f-42d95f001944)

**Comment by e3rd** [comment]
Hustý! Je pro tebe jakžtakž snadný si to oddebuggovat? Kdyby ti to mělo dát hodně práce, vydám to jako verzi.

Pod řádek `const $n = $(n)` dej tenhle kód

```javascript
    if($n === undefined) {
        console.error("$n is undefined", n, $)
        console.trace()
    }
```

a uvidíme, až se to semele. Protože nevěřim, že `n` je undefined, to by to chcíplo už i na `n.tagName`. Zajímá mě hodnota `n`, pro které selže jQuery varianta.

**Comment by kaha0** [comment]
Lokálně jsem si to upravil, když se zase obejví tak dám vědět. Ale zatim se to stalo pouze v tomhle jednom případě.

Zkoušel jsem to debugovat na tom postu kterej jsem si lokálně uložil, ale moc jsem nezjistil. Vyhodilo to tuhle chybu už na `tagName`, ale před ní to nevypsalo nic (jen spoustukrát jQuery verzi, kterou jsem tam přidal pro debugovací účely, ale nic jinýho)

![e2](https://github.com/e3rd/fb-getridad/assets/89856263/78493275-d266-4e23-a6e0-93873816fbc6)

**Comment by kaha0** [comment]
Jo aha, když n je null tak se nechytí na `n === undefined`. Napadá mě: v prvním screenshotu n.tagName prošlo, ale $n.parents spadlo. Nemůže dojít k tomu, že se to $n nenastaví správně, třeba v nějakym kraním případě jako když n je null nebo undefined?

![e](https://github.com/e3rd/fb-getridad/assets/89856263/cfbfc781-0b2e-494a-8e4a-160dfb2017df)

**Comment by kaha0** [comment]
is_garbage se volá s parametrem null tady:
![e](https://github.com/e3rd/fb-getridad/assets/89856263/43bae7b9-1061-4065-b197-aa05015b70c0)

Ten element USE na tomto místě vypadá takhle (což je divný, ne?):
![e2](https://github.com/e3rd/fb-getridad/assets/89856263/7345b299-c5dd-4356-abda-d1d9b71a0304)

Každopádně když na začátek is_garbage přidam podmínku `if (n === null) return false` tak pro celej post vrátí taky false...

**Comment by kaha0** [comment]
Jo počkat, teď jsem si vzpomněl, to je ten svg element kterej fb skrývá pomocí shadowrootu, a to funguje jenom ve Firefoxu... a já jsem to měl otevřený v Opeře. Už zpětně nezjistim, jestli by to ve Firefoxu fungovalo, ale pokud se to znova neobjeví tak bych to bral jako že všechno ok. Pardon za mystifikaci :D

**Comment by e3rd** [comment]
Aha, takže dobrý, zatim zavírám? Jenom jsem to tak projel. Jo, javascriptový undefined a null jsou lahůdky. Rád se tomu budu kdyžtak věnovat, až na to narazíš.

**Comment by kaha0** [comment]
Jo jo, zavírám, díky :)
