### ISSUE TITLE
Unrecognised mainfest key "browser_specific_settings"

### ISSUE THREAD

**Issue by jakub-trusina** [e3rd/fb-getridad#4]
Hi, I'm having this error in Chrome. What shall I do?

![image](https://user-images.githubusercontent.com/61409691/131512646-e84ed256-7ad0-4443-9336-7eab4ab62485.png)

**Comment by e3rd** [comment]
This one can be safely ignored :) It's due to small incompatibility between Chrome and Firefox WebExtension manifest specs

Thanks for having it reported here!
